spring:
  application:
    name: MEDICALREPSCHEDULE-SERVICE
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacyProject
    username: root
    password: root


server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost