spring:
  application:
    name: MEDICALREPSCHEDULE-SERVICE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:pharmacyProject
    username: sa
    password:
    driver-class-name: org.h2.Driver  
  h2:
    console:
      enabled: true
      path: /h2-console
       
server:
  port: 5000
  error:
    include-stacktrace: never

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost