eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8083
spring:
  application:
    name: AUTHORIZATION-SERVICE
  jpa:    hibernate: 
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    
    url: jdbc:mysql://ij018-sufiyan-mfpe.ccoanq845ewc.us-east-2.rds.amazonaws.com:3306/pharmacyProject
    username: admin
    password: sufiyan123
    driver-class-name: com.mysql.cj.jdbc.Driver
  


