spring:
  application:
    name: PHARMACYSUPPLY-SERVICE
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://ij018-sufiyan-mfpe.ccoanq845ewc.us-east-2.rds.amazonaws.com:3306/pharmacyProject
    username: admin
    password: sufiyan123


server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost